### ISSUE TITLE
Unclear support for OCI-runtime specification

### ISSUE THREAD

**Issue by Silvanoc** [projectatomic/buildah#259]
The description of the project clearly states that the focus is on the OCI-image specification, but I'm unsure if subcommands 'config' and 'inspect' are supposed to consume and generate OCI-runtime configurations.

Could you please give some insights on the current status (I couldn't find any reference to the OCI-runtime specification in the current code, but I'd like you to confirm it) and the plans for the future?

**Comment by Silvanoc** [comment]
I'm sorry that I'm asking this way because I couldn't find any documentation about a dedicated mailing-list.

**Comment by nalind** [comment]
No worries.  The [image specification](https://github.com/opencontainers/image-spec/blob/master/spec.md) specifies that images contain a [configuration](https://github.com/opencontainers/image-spec/blob/master/config.md), but the configuration object is optional, and for reasons I haven't really looked into, it isn't just the [runtime spec](https://github.com/opencontainers/runtime-spec/blob/master/config.md) incorporated by reference.

The `config` command tweaks what's in the image's configuration object, or rather, the in-progress one that we also use for `run` commands and can later commit to an image.  (The `run` command has to read that object and use it to generate a runtime configuration for [runc](https://github.com/opencontainers/runc), and it does that in more or less the way [cri-o](https://github.com/kubernetes-incubator/cri-o) does.)

The `inspect` command's output is just the set of information that we keep on-hand about a container that we're working with.  It contains the configuration information maintained in two formats - the OCI format, and one that's compatible with Docker's schema 2, version 2.  We keep the information around in both formats because while they're highly similar, the two formats also each include information that the other doesn't.  Maintaining the information in both formats, updating both as we process `config` commands that affect one or both, lets us avoid losing any of that information until we actually have to throw it away, i.e. when we commit an image using a configuration format that doesn't carry that information.

We could have tried to define a single structure that included fields from both; my guess was that it would have been more work in the long run.  If that turns out to be a wrong guess if/when the image spec gets revised and we go to add support for it, we can change that.  We currently carry the annotations for the OCI manifest format in a field of its own, and not as part of an OCI manifest structure, so it's not like that's set in stone.

Anyway, I don't currently have any plans to change the output format for `inspect`.  That can change, of course, if there's a case for doing so, and it's possible that other maintainers are thinking about it.

Apologies for the wall of text here, but you had a good question, and I want to provide a thorough answer.  Please follow up if I've left out something.  Thanks!

**Comment by Silvanoc** [comment]
@nalind thank you for taking your time for writing your "wall of text"! 😃

I have the impression that Docker was the "inspiration" for the OCI-runtime configuration and the OCI-image configuration:

- For me the OCI-_image_ configuration specifies kind of what you would specify with "docker _build_" and

- the OCI-_runtime_ configuration specifies kind of what you would specify with "docker _run_".

Therefore the OCI-image configuration announces the intention of exposing certain ports and mounting certain resources, but they are actually exposed/mounted with the OCI-runtime configuration.

What I interpret from your comment is that buildah can't be used to generate an OCI-runtime configuration, right?

BTW, do you have a link to enlighten how cri-o does the generation of the OCI-runtime configuration out of the OCI-image configuration?

**Comment by nalind** [comment]
The [OCI FAQ](https://www.opencontainers.org/faq#faq9) probably describes the origin of the OCI specs better than I can, but I gather that the similarity between the formats is intentional.

`buildah` generates a runtime configuration when it needs to invoke `runc`, either as part of `buildah run` or when processing `RUN` instructions in a Dockerfile, but it's only meant to be a temporary file that we produce so that we can run `runc`.  It's not meant as a general tool for creating runtime configurations.

Both `cri-o` and `buildah` look at various parts of the configuration information in the image and use the `generate` package from the [`runtime-tools`](https://github.com/opencontainers/runtime-tools) repository to apply those settings to a template value (in [container_create.go](https://github.com/kubernetes-incubator/cri-o/blob/master/server/container_create.go#L509) and [run.go](https://github.com/projectatomic/buildah/blob/master/run.go#L142), respectively).  That value is then encoded as JSON to produce the contents for the configuration file.

The `runtime-tools` package also contains a `oci-runtime-tool` tool which can be used to generate a configuration file with settings passed to its `generate` command, if you're looking for something that's more scripting-friendly.

**Comment by rhatdan** [comment]
This information seems like a great beginning of a blog...

**Comment by rhatdan** [comment]
@Silvanoc Can I close this issue now?

**Comment by Silvanoc** [comment]
@rhatdan sorry for not reponding sooner.

Just let me try to reformulate what @nalind to make sure that I got it right and you can then close the issue:
The configuration options provided with the image are being used as defaults to generate OCI-runtime configurations, right?

**Comment by nalind** [comment]
@Silvanoc yup, that's a good short version.  The format those options are recorded in isn't a runtime configuration, so when we need a runtime configuration for running a command, we incorporate those options into one that we generate.

**Comment by ripcurld0** [comment]
Thanks @Silvanoc and @nalind 
Closing the ticket now.
