### ISSUE TITLE
Failed to list all images

### ISSUE THREAD

**Issue by surajnarwade** [projectatomic/buildah#469]
I followed https://github.com/projectatomic/buildah/blob/master/install.md to install `buildah`,

Now I am trying to list all images,

```
$ buildah images
mkdir /var/run/containers/storage: permission denied
mkdir /var/run/containers/storage: permission denied
```
It's failing :(

**Comment by ripcurld0** [comment]
Probably your user doesn't have permissions to create `/var/run/containers/storage`. Thus try running `buildah` using `sudo`.

**Comment by rhatdan** [comment]
buildah has to run as root.

**Comment by surajnarwade** [comment]
Thanks @ripcurld0  @rhatdan for clarification. Here's one more question, So `sudo buildah images` will not list images same as `docker images` ?

**Comment by ripcurld0** [comment]
@surajnarwade that's probably right.
`Docker` is storing the images in `/var/lib/docker/<storagename>` by default.
For example, since my storage driver is `overlay2` then the images are stored under `/var/lib/docker/overlay2`.
Even if I try to read from that directory in order to list images, it's likely that the way the images are stored is not according to `OCI` and therefore `buildah` won't be able to list them.

@rhatdan correct me if I'm wrong.

**Comment by rhatdan** [comment]
Yes buildah/CRI-O/Podman and skopeo can all share the same storage.  Docker has its own private storage.  You can move content out of a Docker daemons storage into containers/storage using skopeo though.

**Comment by rhatdan** [comment]
Right buildah shares github.com/containers/storage with other tools like CRI-O, podman, but not Docker.  Docker has a private container storage.  You can use skopeo to copy images out of a local Docker container storage into cri-o/buildah/podman container storage.  But when listing images these tools will only list "container/storage" images.
