### ISSUE TITLE
devmapper: Unknown option overlay.override_kernel_check

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/buildah#526]
...when invoking with `--storage-driver devicemapper`:

    # buildah --storage-driver devicemapper from fedora
    devmapper: Unknown option overlay.override_kernel_check
    devmapper: Unknown option overlay.override_kernel_check

Cause: `override_kernel_check = "true"` in `/etc/containers/storage.conf`. I'm seeing this on Fedora 27 and RHEL 7.5.

This is a followup to #309, which appears to have been "solved" by defaulting to overlay. If devicemapper is unsupported, it should probably be deprecated with a mroe helpful message.

**Comment by rhatdan** [comment]
We should just ignore this flag in containers/storage.  @nalind WDYT?

**Comment by rhatdan** [comment]
Actually this is strange looks like the code is still using the "overlay" specified in the storage.conf to specify the option even though the command line overrode the option.  Perhaps we should just clear options when the user overrides  in the command.  Since the options are per driver, we should drop the config.

**Comment by rhatdan** [comment]
Since #538 is merged, I am closing this issue.
