### ISSUE TITLE
Regression in storage driver support 0.11 -> 0.12

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#547]
**Description**
Not sure if this is actually an issue (or expected), but I noticed a change in behaviour between 0.11 -> 0.12 and the 'tolerance' of the overlayfs driver detection (did this change?).

I was using buildah 0.11 on a stock CentOS install without issue, and when upgrading to 0.12 the overlayfs warnings started and functionality broke completely. I can fix the reported overlayfs issue (XFS not configured correctly) but wondering if this breakage is/was intentional.

**Steps to reproduce the issue:**
1. `# rpm -q buildah`
`buildah-0.11-3.git49095a8.el7.x86_64`
2. `# buildah run working-container -- whoami`
`root`
3. `# rpm -q buildah`
`buildah-0.12-1.git8badcc2.el7.x86_64`
4. `# buildah run working-container -- whoami`
`kernel does not support overlay fs: driver not supported`
`kernel does not support overlay fs: driver not supported`

**Describe the results you received:**
Error regarding overlay fs driver support.

**Describe the results you expected:**
Successful execution of 'buildah run'

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.12-1.git8badcc2.el7.x86_64
```

**Output of `buildah version`:**

```
buildah version 0.12 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.4.1708 (Core)
```

**Output of `uname -a`:**

```
3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
I think that we were updating containers/storage which added a new check to make sure xfs was configured correctly.  That must be what you are seeing.

**Comment by nalind** [comment]
That version bump pulled in the [change](https://github.com/containers/storage/pull/144) in the storage library that switched it from warning about possible errors when the underlying system for an upper directory doesn't report `d_type` information to making it a fatal error, so this much was expected.  When multiple lower directories are used, it's also required for lowers, except for the lowest one.
The main symptom of not having `d_type` available was that you would see whiteout entries partially showing up in directory listings in mounted overlay filesystems, when, as whiteout entries, they should not have.  They would take the form of items in directories that tools like `ls` would "know" were there, but which were otherwise unusable.
