### ISSUE TITLE
Feature: buildah-push rkt support

### ISSUE THREAD

**Issue by taqtiqa-mark** [projectatomic/buildah#563]
Thanks for all the effort on Buildah, and for making it open source.

**Description**
Rkt has the most elegant discovery mechanism.  It eliminates the need for container registry infrastructure/headaches, whether in public or private clouds.

I don't think it will go away anytime soon.

[woofwoofinc/docker2aci](https://github.com/woofwoofinc/docker2aci) has a working example of the code required to convert from oci to aci.

It would be nice to do this, see [rkt's discovery description](https://github.com/appc/spec/blob/master/spec/discovery.md), where rkt-version -> oci-tag:

````bash
signing_key=/path/to/key.asc
buildah push --rkt-key=${signing_key} ${OCI_NAME}:${OCI_TAG} 
#produces {name}-{version}.aci and {name}-{version}.aci.asc and {name}-{version}-public.gpg
buildah push --rkt-key=${signing_key} --rkt-os=linux --rkt-arch=amd64 ${OCI_NAME}:${OCI_TAG} 
#produces {name}-{version}-{os}-{arch}.aci and {name}-{version}-{os}-{arch}.aci.asc and {name}-{version}-public.gpg
````

**Comment by rhatdan** [comment]
@mtrmac WDYT

**Comment by rhatdan** [comment]
@vbatts Thoughts?

**Comment by mtrmac** [comment]
\*shrug\* If someone wanted to do the work to implement an ACI transport for c/image, I don’t see a reason to refuse such a contribution.

- There would probably be a performance cost in unpacking and re-packing the tarballs, but docker2aci is paying the same cost.
- ACI does not support image layering, which makes the cost more or less unavoidable, at least for a c/image backend; c/image only understands images to the level of layers. (There already is a precedent, in the OSTree transport, for unpacking the layer tarballs.)  Alternatively, it might be more efficient to write a straight buildah→ACI output implementation, generating the tarball with the `rootfs` directory directly from c/storage—more efficient, but not at all reusable.
- I’m less sure about a nice generic way to incorporate the signing, but it’s easy to imagine a hack that works (as the example shows, teaching `buildah` etc. about the RKT keys specially).
- It’s not obvious that that work could reuse that much of docker2aci, but I have only spent about 2 minutes checking. (Of course, a shell script running buildah+docker2aci should be easy; but also much less efficient than native c/image integration.)

Overall, though, given https://github.com/rkt/rkt/blob/master/ROADMAP.md saying that OCI “will become the preferred way over appc” it seems hard to recommend that anyone should take on the work to implement such a backend—especially if the point is discovery&distribution rather than the image format. @vbatts can probably give much more insight about the viability and status of the standards and projects, though.


For simplifying the distribution of OCI/Docker images, instead of throwing the OCI infrastructure out wholesale, I’d suggest just focusing on the distribution problem directly.

For example, AFAICS the docker/distribution format, for shipping read-only images with no online update facility, can be backed by an ordinary static HTTP server (it only really needs to set `Content-Type` and `Content-Length` correctly). So, it should be possible to write a configuration for an ordinary HTTP server to serve as a docker/distribution server, and to write a (very simple) containers/image transport that generates the static file layout serving images in such a server. 

Would that be interesting WRT “eliminating the need for container registry infrastructure/headaches”, or am I missing the mark entirely?

**Comment by vbatts** [comment]
Is this to facilitate a migration?

**Comment by vbatts** [comment]
buildah is already _very_ similar workflow to the now deprecated 
`acbuild` tool. I'm feeling like a rkt build workflow would be easier to 
just import from an OCI image into rkt, and let rkt do its translation 
into an aci image on the back-end.

**Comment by taqtiqa-mark** [comment]
All valid points.  I don't know of the docker spec so can't comment about the docker discovery/distribution mechanism.   
In my expereince the rkt spec is the simplest possible - right now `rkt fetch taqtiqa.io/....` uses a Route53, AWS-S3 routing rules to point to github release files - simple. There is a 2GB github-ceiling in this approach.

There are workarounds, so closing.

**Comment by taqtiqa-mark** [comment]
Actually, I'd like to keep this open.  As @mtrmac indicates, such functionality isn't opposed.  He's correct the appc indicates the OCI spec are preferred. But.... that spec isn't finished.  Its not yet clear to me its an improvement, i.e. I should migrate from rkt.

The appc Roadmap page also indicates rkt:
- will continue to support the current discovery protocol/mechanism.
- version 1 deprecation isn't contemplated

I've tried to read the [OCI distribution spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md
) - ouch.  All that to download a zip file?  It seems trust, identity, and provenance models are being intermingled and that's causing the pain.

I won't pretend to even partly understand it.  I can say this. In a couple of hours I read and understood the appc discovery mechanism, and worked out a project could distribute signed opensource containers **without writing any code** - just set some configuration values on Amazon's and github's services and you're good to go:  Opensource projects with container distribution infrastructure superior to DockerHub.  Not bad.

That is a nontrivial point for opensource projects.  

All the above is by way of making the case that it would be nice to have a build tool that considered `rkt` v1 a first class citizen.

Thanks for considering.

**Comment by taqtiqa-mark** [comment]
@mtrmac, point taken. As I said I don't pretend to understand the use cases (business models) that are in mind for the spec.  If downloading OCI containers is just using the web standards for zip files, then I'd imaging uploading them is the same ;)  Of course there are newer interesting update mechanisms, such as git-LFS, etc. but then the spec would be define implementation details.

As I said I don't pretend to understand what use cases are driving the specs.

Rkt uses std key-trust mechanisms so you can preauthorize the keys - its been awhile but from memory this is what I did.   We agree, you can't stop people electrocuting themselves and that is no reason to turn off electricity.

I reopened this in the following spirit, before the code comes the idea and the use case.  I've shared my ideas and the use case.  

It seems the project doesn't yet reject the use case.

**Comment by rhatdan** [comment]
Since RKT is being deemphasized, I am going to close this issue.
